### PR TITLE
initial commit for grid extension

### PR DESCRIPTION
**Pull request by philvarner**
Initial commit for Grid extension.

### CODE REVIEW

**Comment by drwelby** [comment]
Concatenating the grid system and cell identifier versus having one field for each? 

It seems like it would be easier to query by cell ID if you don't have to add the grid identifier specified by this extension. 

I supposed you could have collisions between competing quadkey systems, for example. Would aggregating on two fields be  problematic anywhere?

**Comment by drwelby** [comment]
We could pilot this in Maxar ARD in an update happening in May. We use our own UTM grid so we would use:

`MXRA-Z<zone>-<quadkey>`

**Comment by philvarner** [comment]
That would be great. You can add this gridding to the spec to, even though it's maxar specific, as long as it's standard among where it's used.

**Comment by philvarner** [comment]
as for having this in a normalized format as opposed to a single field -- I don't think anyone would search a stac api based on any single one of those fields, so I don't think there would be any benefit there. Elasticsearch and postgres allow you to aggregate over a composite key, but I don't know if those results will actually get cached, so it becomes a more expensive operation each time.

**Comment by philvarner** [comment]
@drwelby could you take a final look at this? then I'll merge.

**Comment by drwelby** [comment]
Looks good to me

**Pull request merged**
